pool:
  name: 'Default'
  demands:
   - agent.name -equals DESKTOP-GSPVN3D-Win11
   - agent.version -equals 2.206.1

variables:
  solution: '$(Build.SourcesDirectory)/NetForce/NetForce.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: true

- checkout: self
  fetchDepth: 1

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:PublishReadyToRun=false'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArchitecture: 'x64'
